name: Update CIMG.h
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  pull-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Fetch the latest tag (could be buggy)
        uses: actions/github-script@v7
        id: latest-tag
        with:
          result-encoding: string
          script: |
              return (await github.rest.repos.listTags({ owner: 'GreycLab', repo: 'CImg', per_page: 28 })).data[27].name
      - if: ${{steps.latest-tag.outputs.result=='v.3.3.1'}}
        name: Exit if up-to-date
        run: exit 0
      - name: Download new CImg version
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://github.com/GreycLab/CImg/raw/${{ steps.latest-tag.outputs.result }}/CImg.h'
          location: 'src'
      - name: Commit new CImg version (and update script)
        run: |
          # mv -f src/CImg418.h src/CImg.h
          sed -i 's/v.3.3.1/${{ steps.latest-tag.outputs.result }}/' .github/workflows/cimg.yml
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git commit -am "Update CImg.h to ${{ steps.latest-tag.outputs.result }}"
          git push
