name: Update CIMG.h
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  check-version:
    name: Check for updates
    runs-on: ubuntu-latest
    steps:
      - name: Fetch the latest tag (could be buggy)
        uses: actions/github-script@v7
        id: latest-tag
        with:
          result-encoding: string
          script: |
              return (await github.rest.repos.listTags({ owner: 'GreycLab', repo: 'CImg', per_page: 28 })).data[27].name
  pull-file:
    name: Update CImg
    runs-on: ubuntu-latest
    needs: check-version
    if: ${{ needs.check-version.latest-tag.outputs.result != 'v.3.3.2' }}
    steps:
      - uses: actions/checkout@v4
        name: Checkout this repository
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
      - name: Download new CImg version
        uses: carlosperate/download-file-action@v2
        with:
          file-url: 'https://github.com/GreycLab/CImg/raw/${{ steps.latest-tag.outputs.result }}/CImg.h'
          location: 'src'
      - name: Commit new CImg version (and update script)
        run: |
          sed -i 's/v.3.3.2/${{ needs.check-version.latest-tag.outputs.result }}/' .github/workflows/cimg.yml
          git config user.name 'GitHub Actions'
          git config user.email 'actions@github.com'
          git commit -am "Update CImg to ${{ needs.check-version.latest-tag.outputs.result }}"
          git push
