name: Test GitHub Script
on:
  push:
    path
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        id: tag
        with:
          script: |
            return github.rest.repos.listTags(
              {owner: 'GreycLab', repo: 'CImg', per_page: 1, page: 1}).data
      - run: echo ${{ steps.tag.outputs.result }}
